export const BRAND_CONFIG = {
  name: "KRAXXSEC",
  parentBrand: "KRAXX",
  subtitle: "CYBERSECURITY & SECURITY ENGINEERING",
  tagline: "Find the weakness. Fix the risk.",
  heroSub: "We test the systems businesses depend on.",
  shortDescription: "KRAXXSEC provides web application security testing, API security assessments, vulnerability assessments, security engineering, and cybersecurity consulting for modern businesses.",
  founder: {
    name: "Mohamed Basil",
    role: "Founder & Principal Cybersecurity Consultant",
    bio: "Independent cybersecurity practice focused on helping organizations discover, understand, and reduce security risk through hands-on technical assessments.",
    github: "https://github.com/Basilmellow",
    linkedin: "https://www.linkedin.com/in/mohamed-basil-966a8225a/",
  },
  siteUrl: process.env.NEXT_PUBLIC_SITE_URL || "https://kraxxsec.com",
  contactEmail: process.env.NEXT_PUBLIC_CONTACT_EMAIL || "assessment@kraxxsec.com",
  statusStrip: [
    { label: "ASSESSMENT ENGINE", status: "ONLINE", ready: true },
    { label: "APPLICATIONS", status: "READY", ready: true },
    { label: "API SECURITY", status: "READY", ready: true },
    { label: "INFRASTRUCTURE", status: "READY", ready: true },
    { label: "MODE", status: "AUTHORIZED TESTING ONLY", ready: false },
  ],
  navItems: [
    { id: "surface", label: "01 / SURFACE", href: "/#surface" },
    { id: "test", label: "02 / TEST", href: "/#test" },
    { id: "verify", label: "03 / VERIFY", href: "/#verify" },
    { id: "report", label: "04 / REPORT", href: "/#report" },
    { id: "fix", label: "05 / FIX", href: "/#fix" },
    { id: "services", label: "SERVICES", href: "/services" },
    { id: "research", label: "RESEARCH", href: "/research" },
    { id: "about", label: "ABOUT", href: "/about" },
    { id: "pricing", label: "PRICING", href: "/#pricing" },
    { id: "contact", label: "CONTACT", href: "/contact" },
  ],
};
